apiVersion: v1
kind: Pod
metadata:
 name: multi-pod
 labels:
  type: webserver
  author: mahmoud
spec:
 containers:
  - name: c1
    image: nginx
  - name: c2
    image: httpd
  - name: c3
    image: ubuntu

